apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hivebox
  name: hivebox-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hivebox
  strategy: {}
  template:
    metadata:
      labels:
        app: hivebox
    spec:
      containers:
        - image: ghcr.io/abdelrahman495/hivebox:latest
          name: hivebox-container
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: hivebox-config-vol
              mountPath: /app/config
              readOnly: true
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: hivebox-config-vol
          configMap:
            name: hivebox-config
status: {}
