name: CI

on:
  push:
    branches:
      - main
      - "phase-*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: Install dependencies
        run: uv sync --group dev

      - name: Lint Python code
        # uses: astral-sh/ruff-action@v3
        run: |
          uv add pylint && uv run pylint app.py sensebox_service.py

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: Dockerfile

      - name: Run unit tests
        run: uv run pytest -vm unit

      - name: Build Docker image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          push: false
          tags: hivebox:${{ github.sha }}

      - name: Run container
        run: |
          docker run -d -p 8000:8000 --name hivebox hivebox:${{ github.sha }}

      - name: Test /version endpoint
        run: |
          echo "Waiting for API to start..."
          until curl -s http://localhost:8000/version > /dev/null; do
            sleep 1
          done

          EXPECTED_VERSION=$(grep '^version' pyproject.toml | cut -d '"' -f2)
          API_VERSION=$(curl -s http://localhost:8000/version | jq -r '.version')

          if [[ "$API_VERSION" != "$EXPECTED_VERSION" ]]; then
              echo "Version mismatch: expected $EXPECTED_VERSION but got $API_VERSION"
              exit 1
          fi

      - name: Stop container
        run: docker stop hivebox

      - name: Run integration tests
        run: uv run pytest -vm integration
