name: Terrascan

on:
  pull_request:
    branches:
      - main
    paths:
      - "k8s/**"

permissions:
  contents: read

jobs:
  terrascan:
    name: terrascan
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Terrascan
        id: terrascan
        continue-on-error: true
        run: |
          docker run --rm \
          --mount type=bind,src=${{ github.workspace }}/k8s,dst=/k8s \
          tenable/terrascan@sha256:1fffb95fd064f53c997da5bb9b2fdb9b14abcad7391fbb7fe42b866358695b16 \
          scan \
          --iac-type "k8s" \
          --iac-dir "/k8s" \
          --policy-type "k8s" \
          --output sarif > terrascan.sarif

          sed -i 's|file:///k8s/|k8s/|g' terrascan.sarif

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        with:
          sarif_file: terrascan.sarif
